server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/productdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  application:
    name: ${APP_NAME:PRODUCT-SERVICE}
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost:9296}


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
