server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/paymentdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost:9296}
